# Generated by Django 4.0.5 on 2022-06-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega_reparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('entrega', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado_revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.IntegerField()),
                ('entrada', models.DateTimeField()),
                ('tipo_reparacion', models.CharField(max_length=20)),
                ('status', models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Ready')], default='m', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('marca_de_carro', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('placa', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('descripcionRev', models.TextField()),
            ],
        ),
    ]
